## 1 
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [28]:
import numpy as np

In [77]:
def ATVMatrix(inpvector, ncol, increasing):
    if(increasing):
        out= np.array([elem ** pow for elem in inpvector for pow in range(ncol)],).reshape(len(inpvector),ncol)
    else:
        out= np.array([elem ** (ncol-1-pow) for elem in inpvector for pow in range(ncol)],).reshape(len(inpvector),ncol)
    return out

inpvector = [1,2,3,4,5,6,7,8]
incmat = np.array(ATVMatrix(inpvector, 4, True))
decmat = np.array(ATVMatrix(inpvector, 4, False))
print("Matrix in increasing order:")
print(incmat)
print("\n\nMatrix in decreasing order:")
print(decmat)

Matrix in increasing order:
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]
 [  1   7  49 343]
 [  1   8  64 512]]


Matrix in decreasing order:
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]
 [343  49   7   1]
 [512  64   8   1]]


## 2
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [107]:
def MovingAvg(inpseq, window):
    try:
        inparr = np.array([inpseq[i:i+window] for i in range(0,len(inpseq)+1-window)])
        mv = np.array([i.mean() for i in inparr])
    except Exception as e:
        print('Exception: ', e)
        return null
    else:
        return mv
    

mv = MovingAvg([10,20,30,40,50,60,70,80,90,100], 4)
print(mv)

[25. 35. 45. 55. 65. 75. 85.]
